### PR TITLE
Add Microsoft User Data

### PR DESCRIPTION
**Pull request by EvanEvan-17**

### CODE REVIEW

**Comment by AlphaBs** [comment]
I'm just curious - does Microsoft server really returns `user_data` property as json object? `MicrosoftUserPayload` seems JWT payload, looks like it need to do additional work ? (e.g parse `access_token` or `id_token` as JWT)

**Comment by EvanEvan-17** [comment]
OK wait, I will add the function to decode id_token payload.

**Comment by EvanEvan-17** [comment]
I've added new function, please review it and merge to your dev branch. If something seems doesn't right, feel free to comment again.

**Comment by AlphaBs** [comment]
does id_token means this?

https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#request-an-id-token-as-well-or-hybrid-flow

I don't think id_token is part of `MicrosoftOAuthResponse`, it should be in `MicrosoftOAuthCode`.

**Comment by EvanEvan-17** [comment]
No, I'll still use 'code' response type not 'id_token' response type, but the ID Token is returned as part of MSAL.NET's `AuthenticationResult` when you use openid scope (which included when using MSAL.NET). So it will be the part of `MicrosoftOAuthResponse`.

**Comment by AlphaBs** [comment]
> does id_token means this?
> 
> https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#request-an-id-token-as-well-or-hybrid-flow
> 
> I don't think id_token is part of `MicrosoftOAuthResponse`, it should be in `MicrosoftOAuthCode`.

Nevermind, id_token is the part of MicrosoftOAuthResponse. 

https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-device-code#successful-authentication-response

Thank you for contributing. After some tests, I'll merge this.

**Comment by EvanEvan-17** [comment]
Make sure to also use 'profile' scope when you test this so user info (name, user name, etc) is not empty, which is included when you use MSAL.NET. 

You can also optionally include 'email' scope when you want to get an email address as part of id_token payload.

**Pull request merged**
